### PR TITLE
deconflict object::types::Rect and content::Rect

### PR DESCRIPTION
**Pull request by gdennie**
`content::Rect {x,y,width,height}` and `object::types::Rect {bottom,left,top,right}` are being used in conflicting ways.
Did research, presented in comments, and provided conversion between representations. Renamed to `ViewRect` and `Rectangle`, respectively, inline with ISO 32000-2-2020 spec.

### CODE REVIEW

**Comment by s3bk** [comment]
First of all thank you for your work. This is a good idea and I will apply it.
But please don't combine code changes with a `rustfmt` run. If you use it for format the parts you changed, fine.
I am aware that the formatting isn't the greatest and could do with some cleanup, but there are areas where `rustfmt` does not help readability.

**Comment by s3bk** [comment]
I have applied your work in 75e33811933d2c64a903d4cf203bd459040bac63, b4599aeb5416c292682cd77051dbfe696c4d5c2f, 7d4bb060bcf8982de3c654cce9b84eda201d202c and db1120c46b44f7d75a9ff1201d2cc7392d07bc05.

If you wish to tackle the formatting we can talk about that.

**Comment by gdennie** [comment]
The formatting changes was a surprise to me but undoing it would have delayed the post awhile.
I will take pains to avoid that happening in any future contribution.

What issues with the formatting need work?

**Comment by s3bk** [comment]
I assumed your formatting changes where unintentional but wanted to say that in case they are intentional, you can work on the formatting.

But I consider it not important, so don't worry about it.

You solved the important problem: Naming. I just had to rename the symbols.

**Pull request closed without merging**
